### PR TITLE
fix index.d.ts

### PR DESCRIPTION
**Pull request by Gavinchen92**
Deleted an extra " }"

### CODE REVIEW

**Comment by saitonakamura** [comment]
@Gavinchen92 super thanks, is it working on your side? (I'm unable to test it right now, sorry) If it is, I'll merge it

**Comment by Gavinchen92** [comment]
its ok!

**Review by saitonakamura — APPROVED** [review]
Nice!

**Comment by saitonakamura** [comment]
Ok, I've merged it, I'll release a new version today

**Comment by saitonakamura** [comment]
@Gavinchen92 I've released it

**Comment by Gavinchen92** [comment]
@saitonakamura thanks

**Pull request merged**
